---
name: Container Release

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - v*

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

permissions:
  contents: read
  packages: write

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  container-release:
    # Ensure test job passes before pushing image.
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2

      - name: Login to Packages Container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container Reference Name
        id: container_ref
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          # Strip git ref prefix from version
          NAME=$(printf '%s' "$GITHUB_REF" | sed -e 's,.*/\(.*\),\1,; s/^v//')
          # Use Docker `latest` tag convention
          [ "$NAME" == "master" ] && NAME=latest
          # Sanitize and expose variables
          safe=$(printf '%s' "$NAME" | tr -d '\n\r')
          echo "ref_name=$safe" >> "$GITHUB_ENV"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.ref_name }}
